"""Duty morning report routes: GET/POST /api/duty-report.

The report itself is generated by the monitoring controller (see
core.report.duty_report); these routes only read it back for the UI
popup / history view, record per-user dismissal, and offer an
admin-only force-regenerate for ops and demos.
"""

from typing import List

from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session

from api.deps.auth import CurrentUser, get_current_user
from api.deps.db import get_session
from api.deps.rbac import AdminOnly
from api.schemas.duty_report_schemas import (
    DutyReportMeta,
    DutyReportResponse,
    DutyReportTodayResponse,
)
from core.exceptions import NotFoundError
from core.logging import get_logger
from core.models.entities import DutyReport, Notification
from core.report.duty_report import force_generate, local_today

logger = get_logger(__name__)
router = APIRouter(prefix="/api/duty-report", tags=["duty-report"])


def _user_dismissed(session: Session, user_id: int, report_id: int) -> bool:
    notif = (
        session.query(Notification)
        .filter(
            Notification.user_id == user_id,
            Notification.type == "duty_report",
            Notification.related_entity_type == "duty_report",
            Notification.related_entity_id == report_id,
        )
        .order_by(Notification.id.desc())
        .first()
    )
    # No notification row means the user wasn't a recipient — never popup.
    return notif is None or bool(notif.is_read)


@router.get("/today", response_model=DutyReportTodayResponse)
def get_today(
    session: Session = Depends(get_session),
    current_user: CurrentUser = Depends(get_current_user),
):
    """Today's report (if ready) and whether to show the morning popup.

    "Today" is computed with the same tz convention the generator uses,
    so the popup and the scheduler always agree on the calendar day.
    """
    report = (
        session.query(DutyReport)
        .filter(
            DutyReport.report_date == local_today(),
            DutyReport.status == DutyReport.STATUS_READY,
        )
        .first()
    )
    if report is None:
        return DutyReportTodayResponse(report=None, show_popup=False)
    recipients = report.recipient_user_ids or []
    show_popup = current_user.user_id in recipients and not _user_dismissed(
        session, current_user.user_id, report.id
    )
    return DutyReportTodayResponse(report=report, show_popup=show_popup)


@router.get("", response_model=List[DutyReportMeta])
def list_reports(
    limit: int = 14,
    session: Session = Depends(get_session),
    current_user: CurrentUser = Depends(get_current_user),
):
    """Recent reports, newest first — metadata only (no sections)."""
    limit = max(1, min(limit, 90))
    return (
        session.query(DutyReport)
        .order_by(DutyReport.report_date.desc())
        .limit(limit)
        .all()
    )


@router.get("/{report_id}", response_model=DutyReportResponse)
def get_report(
    report_id: int,
    session: Session = Depends(get_session),
    current_user: CurrentUser = Depends(get_current_user),
):
    report = session.query(DutyReport).filter(DutyReport.id == report_id).first()
    if report is None:
        raise NotFoundError("Duty report not found")
    return report


@router.post("/{report_id}/dismiss", status_code=status.HTTP_204_NO_CONTENT)
def dismiss_report(
    report_id: int,
    session: Session = Depends(get_session),
    current_user: CurrentUser = Depends(get_current_user),
):
    """Mark the caller's popup as dismissed (idempotent)."""
    session.query(Notification).filter(
        Notification.user_id == current_user.user_id,
        Notification.type == "duty_report",
        Notification.related_entity_type == "duty_report",
        Notification.related_entity_id == report_id,
    ).update({Notification.is_read: 1})


@router.post("/generate", response_model=DutyReportResponse)
def generate_now(
    current_user: CurrentUser = Depends(AdminOnly),
):
    """Force (re)generate today's report synchronously — ops/demo path."""
    report = force_generate()
    logger.info(
        "duty report {} force-generated by {}", report.report_date, current_user.username
    )
    return report
