"""Scheduled reports generated by the platform itself (no user in the loop).

Currently: the daily duty morning report (值班晨报) — see
:mod:`core.report.duty_report`. Deliberately separate from
:mod:`core.agent` so the deterministic report pipeline has zero
dependency on the optional agent extra; the LLM executive summary is an
optional enhancement imported lazily from ``core.agent.duty_summary``.
"""
