"""System/infrastructure entity models."""
from datetime import datetime

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, JSON, String, Text, UniqueConstraint

from core.models.database import Base
from core.models.constants import SupportGroupSourceType


class Schedule(Base):
    """
    Weekly duty schedule — maps a week to an on-duty Ops Member.

    Platform Admin assigns one Ops Member per week. The Issue engine
    uses GET /api/schedules/current to determine who to auto-assign
    new Issues to.

    Attributes:
        id: Auto-increment primary key.
        week_start_date: ISO date string (YYYY-MM-DD) for the Monday of the duty week.
        assignee_id: FK to users.id — the Ops Member on duty that week.
        created_by: FK to users.id — the Admin who created this schedule entry.
        note: Optional free-text note (e.g. "covering for Alice").
        created_at: Creation timestamp.
        updated_at: Last update timestamp.
    """

    __tablename__ = "schedules"

    id = Column(Integer, primary_key=True, autoincrement=True)
    start_time = Column(DateTime, nullable=False)
    end_time = Column(DateTime, nullable=False)
    assignee_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    duty_role = Column(String(50), nullable=False, default="Primary")
    note = Column(Text, nullable=True, default="")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class DutyReport(Base):
    """
    Daily duty morning report (值班晨报) — one generated report per local
    calendar day.

    Generated by the monitoring controller shortly after the configured
    send time (default 08:30 local). The UNIQUE ``report_date`` doubles as
    the multi-worker / restart-safe dedup: whichever worker inserts the
    claim row first generates; an IntegrityError means the race was lost.

    Attributes:
        id: Auto-increment primary key.
        report_date: Local calendar day (ISO ``YYYY-MM-DD``), unique.
        status: ``generating`` while being built, ``ready`` once complete.
        window_start: Naive-UTC start of the lookback window (24h sections).
        window_end: Naive-UTC generation time (end of the lookback window).
        sections: JSON — the five deterministic sections plus a stats block.
        llm_summary: JSON DutyReportSummary dict; null when degraded to
            template-only (LLM unavailable or failed).
        llm_status: ``ok`` | ``skipped`` | ``failed``.
        email_status: ``pending`` | ``sent`` | ``partial`` | ``failed`` | ``skipped``.
        recipient_user_ids: JSON list of on-duty user ids at generation time
            (the email + popup audience).
        created_at: Creation timestamp.
    """

    __tablename__ = "duty_reports"

    STATUS_GENERATING = "generating"
    STATUS_READY = "ready"

    id = Column(Integer, primary_key=True, autoincrement=True)
    report_date = Column(String(10), nullable=False, unique=True, index=True)
    status = Column(String(20), nullable=False, default=STATUS_GENERATING)
    window_start = Column(DateTime, nullable=True)
    window_end = Column(DateTime, nullable=True)
    sections = Column(JSON, nullable=True)
    llm_summary = Column(JSON, nullable=True)
    llm_status = Column(String(20), nullable=False, default="skipped")
    email_status = Column(String(20), nullable=False, default="pending")
    recipient_user_ids = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class Notification(Base):
    """
    In-app notification for users.

    Created automatically when handover status changes (approved/rejected)
    so that the Project Owner is informed of the outcome.

    Attributes:
        id: Auto-increment primary key.
        user_id: FK to users.id — the recipient.
        title: Short notification title.
        message: Notification body text.
        type: Notification category (handover_approved, handover_rejected, etc.).
        is_read: Whether the user has read this notification (0=unread, 1=read).
        related_entity_type: Optional entity type for linking (e.g. "product").
        related_entity_id: Optional entity ID for linking.
        created_at: Creation timestamp.
    """

    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String(512), nullable=False)
    message = Column(Text, nullable=True, default="")
    type = Column(String(50), nullable=False)
    is_read = Column(Integer, nullable=False, default=0)  # 0=unread, 1=read
    related_entity_type = Column(String(50), nullable=True)
    related_entity_id = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class AuditLog(Base):
    """
    Audit log — records all write operations for traceability.

    Attributes:
        id: Auto-increment primary key.
        user_id: FK to users.id — who performed the action.
        action: The action performed (create, update, delete, handover, approve, reject, etc.).
        entity_type: The type of entity affected (project, product, job, application, issue, schedule).
        entity_id: The ID of the affected entity.
        old_value: JSON snapshot of the entity before the change (null for create).
        new_value: JSON snapshot of the entity after the change (null for delete).
        timestamp: When the action was performed.
    """

    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    action = Column(String(50), nullable=False)
    entity_type = Column(String(50), nullable=False)
    entity_id = Column(Integer, nullable=False)
    old_value = Column(JSON, nullable=True)
    new_value = Column(JSON, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)


class ApiKey(Base):
    """
    API Key for external system authentication.

    External systems (Mock Product, Mock MMP, etc.) use API Keys
    instead of JWT tokens to authenticate with the Ops platform.

    Attributes:
        id: Auto-increment primary key.
        name: Human-readable name for this key.
        key_hash: SHA-256 hash of the API key (never store plaintext).
        key_prefix: First 8 chars of the key for identification.
        created_by: FK to users.id — the Admin who created this key.
        is_active: Whether this key is currently active.
        created_at: Creation timestamp.
    """

    __tablename__ = "api_keys"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255), nullable=False)
    key_hash = Column(String(64), nullable=False, unique=True)
    key_prefix = Column(String(8), nullable=False)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    is_active = Column(Integer, nullable=False, default=1)  # 1=active, 0=revoked (Integer for YugabyteDB compat)
    created_at = Column(DateTime, default=datetime.utcnow)


class SupportGroup(Base):
    """Structured support-group registry for group-aware Ops ownership."""

    __tablename__ = "support_groups"
    __table_args__ = (
        UniqueConstraint("group_key", name="uq_support_groups_group_key"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    group_key = Column(String(255), nullable=False)
    group_name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True, default="")
    source_type = Column(String(50), nullable=False, default=SupportGroupSourceType.MANUAL)
    external_ref = Column(String(512), nullable=True, default="")
    sync_status = Column(String(50), nullable=True, default="")
    last_synced_at = Column(DateTime, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
